// <auto-generated />
using System;
using Blazerize_demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazerize_demo.Migrations
{
    [DbContext(typeof(WagensContext))]
    [Migration("20260421134804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Blazerize_demo.Models.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WagenId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WagenId");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("Blazerize_demo.Models.Wagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlacklistContainers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeldigeLedigingen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kenteken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Lock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoReads")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Online")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotaalKg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wagens");
                });

            modelBuilder.Entity("Blazerize_demo.Models.Label", b =>
                {
                    b.HasOne("Blazerize_demo.Models.Wagen", null)
                        .WithMany("Labels")
                        .HasForeignKey("WagenId");
                });

            modelBuilder.Entity("Blazerize_demo.Models.Wagen", b =>
                {
                    b.Navigation("Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
