// <auto-generated />
using System;
using Blazerize_demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazerize_demo.Migrations
{
    [DbContext(typeof(WagensContext))]
    [Migration("20260422151313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Blazerize_demo.Models.Datum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateDatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotaalKg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("WagenKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WagenKey");

                    b.ToTable("Datum");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotaalKg = 22,
                            WagenKey = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotaalKg = 44,
                            WagenKey = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotaalKg = 33,
                            WagenKey = 2
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotaalKg = 55,
                            WagenKey = 2
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotaalKg = 12,
                            WagenKey = 3
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotaalKg = 32,
                            WagenKey = 3
                        });
                });

            modelBuilder.Entity("Blazerize_demo.Models.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("WagenKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WagenKey");

                    b.ToTable("Label");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GFT",
                            WagenKey = 1,
                            isActive = false
                        },
                        new
                        {
                            Id = 2,
                            Name = "PMD",
                            WagenKey = 1,
                            isActive = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "GFT",
                            WagenKey = 2,
                            isActive = true
                        },
                        new
                        {
                            Id = 4,
                            Name = "PMD",
                            WagenKey = 2,
                            isActive = true
                        },
                        new
                        {
                            Id = 5,
                            Name = "GFT",
                            WagenKey = 3,
                            isActive = false
                        },
                        new
                        {
                            Id = 6,
                            Name = "PMD",
                            WagenKey = 3,
                            isActive = false
                        });
                });

            modelBuilder.Entity("Blazerize_demo.Models.Wagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Diftar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kenteken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wagen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDatum = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diftar = 0,
                            Kenteken = "11-TST-1",
                            UpdateDatum = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Versie = "Test"
                        },
                        new
                        {
                            Id = 2,
                            CreateDatum = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diftar = 1,
                            Kenteken = "22-TST-2",
                            UpdateDatum = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Versie = "Test"
                        },
                        new
                        {
                            Id = 3,
                            CreateDatum = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diftar = 0,
                            Kenteken = "33-TST-3",
                            UpdateDatum = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Versie = "Test"
                        });
                });

            modelBuilder.Entity("Blazerize_demo.Models.Datum", b =>
                {
                    b.HasOne("Blazerize_demo.Models.Wagen", "Wagen")
                        .WithMany("Datums")
                        .HasForeignKey("WagenKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wagen");
                });

            modelBuilder.Entity("Blazerize_demo.Models.Label", b =>
                {
                    b.HasOne("Blazerize_demo.Models.Wagen", "Wagen")
                        .WithMany("Labels")
                        .HasForeignKey("WagenKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wagen");
                });

            modelBuilder.Entity("Blazerize_demo.Models.Wagen", b =>
                {
                    b.Navigation("Datums");

                    b.Navigation("Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
